# version: 1.0.0

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """
$directory\
$character

"""
right_format = """
$git_branch\
$fossil_branch\
$git_commit\
$git_status\
$git_metrics\
$hg_branch\
$custom\
$status\
$cmd_duration\
$os"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = " "
disabled = false


[directory]
home_symbol = ""
truncation_length = 2
truncation_symbol=""
read_only = " "
use_os_path_sep = true
style = "blue"
format = '[$path]($style)[$read_only]($read_only_style) '
repo_root_style = 'italic yellow'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[cmd_duration]
format = "[◄ $duration ](italic bright-blue)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](blue italic)"

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"

[git_branch]
format = " [$branch$symbol(:$remote_branch)]($style)"
symbol = "[](bold italic bright-cyan)"
style = "bright-cyan"
truncation_symbol = "⋯"
truncation_length = 11
only_attached = true

[git_metrics]
format = '( [$added]($added_style))([$deleted]($deleted_style))'
added_style = 'dimmed green'
deleted_style = 'dimmed red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic bright-blue"
format = "([$staged$modified$untracked$renamed$deleted$conflicted$stashed]($style))"
conflicted = "[ 󱔷 ](italic bright-magenta)"
untracked = "[ 󰾙 ](italic bright-yellow)"
stashed = "[ 󱇼 ](dimmed white)"
modified = "[  ](dimmed red)"
staged = "[ 󱔲 [$count](bold white)│](italic bright-cyan)"
deleted = "[ ](bright-red) "

[lua]
format = " [${symbol}]($style)"
version_format = "${raw}"
symbol = " "
style = "bold bright-purple"

# [nodejs]
# format = " [ ](bold bright-green)"
# detect_files = ["package-lock.json", "yarn.lock"]
# detect_extensions = [".js", ".ts"]
#
[python]
format = "[$symbol]($style)"
symbol = ""
version_format = "${raw}"
style = "bold bright-yellow"

[rust]
format = "[$symbol]($style)"
symbol = ""
version_format = "${raw}"
style = "bold red"

[package]
format = "[$symbol]($style)"
version_format = "${raw}"
symbol = ""
style = "dimmed yellow italic bold"

[aws]
disabled = false
format = "[$symbol $profile $region]($style)"
style = "bold yellow"
symbol = ""

[c]
symbol = ""
format = "[$symbol]($style)"
style = "blue"


[docker_context]
symbol = ""
format = "[$symbol$context]($style)"

[golang]
symbol = ""
format = "[$symbol]($style)"

[java]
symbol = "󰬷"
format = "[$symbol]($style)"
style = "bright-red"


