[manager]

sort_by = "natural"
show_hidden = false
ratio = [1, 2, 5]

[opener]
edit = [
{ run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" }
]
play = [
	{ run = 'vlc "$@"', orphan = true, for = "unix" },
]


