theme = "catppuccin_mocha"

[editor]
line-number = "relative"
auto-save = true
true-color = true
preview-completion-insert = true
completion-trigger-len = 1
auto-format = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
rainbow-option = "normal"  # supports "normal", "dim", "none"

[editor.inline-diagnostics]
cursor-line="error"

[editor.lsp]
enable = true
# display-inlay-hints = true
display-messages = true

[keys.normal]
"C-p" = ":open ~/coding/"
"C-d" = ":open ~/.dotfiles/"
C-g = [":new", ":insert-output lazygit", ":buffer-close", ":redraw"]
C-f = [":new", ":insert-output yazi", ":buffer-close", ":redraw"]
C-r = ":open %sh run %val{filename}"
a = ["append_mode", "collapse_selection"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]

[keys.normal.space]
space = ":open ~/coding/"
y = ":clipboard-yank"

[keys.select] 
u = ["switch_to_lowercase", "collapse_selection", "normal_mode"]
U = ["switch_to_uppercase", "collapse_selection", "normal_mode"]
p = [":clipboard-paste-after"]
P = [":clipboard-paste-before"]


[editor.statusline]
left = ["mode","spacer", "version-control"]
center = []
right = ["file-base-name", "spinner", "spacer","workspace-diagnostics", "spacer", "position", "file-modification-indicator"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

