# [[language]]
# name = "go"
# scope = "main.go"
# file-types = ["go"]
# formatter = { command = "gofmt", args = ["-s"] }
# auto-format = true
[[language]]
name = "go"
roots = ["go.work", "go.mod"]
auto-format = true
comment-token = "//"
language-servers = [ "gopls"]

[[language]]
name = "python"
language-servers = ["ruff", "pylsp"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = {enabled = false}

[[language]]
name = "rust"
auto-format = true
roots = [
  "Cargo.toml",
  "Cargo.lock"
]
language-servers = ["rust-analyzer"]
[language-server.rust-analyzer]
command = "/run/current-system/sw/bin/rust-analyzer"
