icons_format = "{icon}"

[theme]
theme = "ctp-mocha"

[icons]
icons = "awesome4"

# [[block]]
# block = "custom"
# hide_when_empty = true
# interval = 30
# command = "sticker -ticker all"
# format = "{$text.str(max_w:17, rot_interval:0.4)}"
# # persistence = true
# [[block.click]]
# button = "left"
# action = "cycle"
# [[block.click]]
# button = "right"
# update = true
#

# [[block]]
# block = "custom"
# interval = 60 
# cycle = ["echo  NBA", "scores nba --game gs", "scores nba --game ny", "scores nba --game den"]
# format = "{$text.str(max_w:20, rot_interval:0.5)}"
# [[block.click]] button = "left" action = "cycle"
# [[block.click]]
# button = "right"
# update = true
#
[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
interval = 10
format = "  $utilization"

[[block]]
block = "memory"
interval = 10 
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "temperature"
interval = 10
format = " $icon $average"

[[block]] 
block = "custom"
interval = 10 
command = '''echo "󰈐 $(sensors | grep fan1 | awk '{print $2; exit}')" '''

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 100.0
warning = 150.0
format = " $icon $available "
# format_alt = " $icon $available / $total "
[[block.click]]
button = "right"
update = true


[[block]]
block = "music"
format_alt = "{$icon $combo.str(max_w:15, rot_interval:0.4) $prev $play $next |}"
format = "{ $icon  $prev $play $next |}"
player = "spotify"
# interface_name_exclude = [".*vlc.*"]
# seek_step_secs = 10
# [[block.click]]
# button = "up"
# action = "volume_up"
# [[block.click]]
# button = "down"
# action = "volume_down"
# [[block.click]]
# button = "forward"
# action = "seek_forward"
# [[block.click]]
# button = "back"
# action = "seek_backward"
#
# [[block]]
# block = "uptime"
# interval = 600

[[block]]
block = "net"
format = "{󰖩 $signal_strength $ssid $frequency| 󰈀 wired} "
inactive_format = "󰖪 "
interval = 30

[[block]]
block = "custom"
cycle = ["mailcli -mail all", "sh ~/.dotfiles/i3/scripts/animanga.sh"]
interval = "once"
[[block.click]]
button = "right"
update = true


[[block]]
block = "custom"
interval = 3600 
# command = "go run ~/coding/projects/weather_bar/weather.go -loc NY"
command = "weather"
# [[block.click]]
# button = "left"
# action = "cycle"
[[block.click]]
button = "right"
update = true

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:' %D %I:%M%p') "

[[block]]
block = "toggle"
format = "$icon 󰅶 "
command_state = "xset q | grep 'DPMS is Disabled'"
command_on = "xset q -dpms s off"
command_off = "xset q +dpms s on"
state_on = "good"
state_off = "idle"
