icons_format = "{icon}"

[theme]
theme = "ctp-mocha"

[icons]
icons = "awesome4"

# [[block]]
# block = "custom"
# hide_when_empty = true
# interval = 600
# # command = "curl -k -s 'https://api.quotable.io/random' | jq -r '.content + ' — ' + .author'"
# command = "echo $(curl -k -s https://api.quotable.io/random | jq -r '.content + .author')"
# format = "{$text.str(max_w:30, rot_interval:0.4)}"
# [[block.click]]
# button = "right"
# update = true
#


[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
interval = 5
format = "  $utilization"

[[block]]
block = "memory"
interval = 5 
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "temperature"
interval = 5
format = " $icon $average"

[[block]]
block = "nvidia_gpu"
if_command = "[ \"$(cat /sys/class/dmi/id/product_name)\" = \"XPS 15 9510\" ]"
interval = 10
format = " 󰾆 $utilization $temperature $clocks "

[[block]] 
block = "custom"
interval = 5 
command = '''echo "󰈐 $(sensors | grep fan1 | awk '{print $2; exit}')" '''

# [[block]]
# block = "music"
# format = "{$icon $combo.str(max_w:15, rot_interval:0.4) $prev $play $next |}"
# format_alt = "{ $icon  $prev $play $next |}"
# player = "spotify"

# [[block]]
# block = "custom"
# # if_command = "[ \"$(playerctl metadata --format '{{playerName}}')\" != \"spotify\"]"
# if_command = "pgrep -f spotify"
# command = "~/.config/i3/scripts/cava-bar.sh"
# persistent = true



[[block]]
block = "net"
format_alt = "{󰖩 $ssid | 󰈀 }$speed_up $speed_down "
format = "{󰖩 $ssid | 󰈀 }" 
inactive_format = "󰖪 "


[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
if_command = "[ \"$(cat /sys/class/dmi/id/product_name)\" = \"XPS 15 9510\" ]"
alert = 100.0
warning = 150.0
format = " $icon $available "
# format_alt = " $icon $available / $total "
[[block.click]]
button = "right"
update = true

# [[block]]
# block = "focused_window"
# [block.format]
# full = " $title.str(max_w:15, rot_interval:0.4) |"

# [[block]]
# block = "uptime"
# interval = 60

[[block]]
block = "custom"
interval = 3600 
command = "echo 󰖕 $(curl -s 'wttr.in/NYC?format=1' | awk -F'+' '{print $2}')"
[[block.click]]
button = "right"
update = true

# [[block]]
# block = "external_ip"
# format = " $city $country_flag "
 
[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:' %D %I:%M%p') "

[[block]]
block = "toggle"
format = "$icon 󰅶 "
command_state = "xset q | grep 'DPMS is Disabled'"
command_on = "xset q -dpms s off"
command_off = "xset q +dpms s on"
state_on = "good"
state_off = "idle"


[[block]]
block = "battery"
format = " $percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
device = "DisplayDevice"
driver = "upower"
missing_format = ""
full_format = ""

