icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
interval = 10
format = "  $utilization"

[[block]]
block = "memory"
interval = 10 
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "temperature"
idle = 28
warning = 35
interval = 10
format = " $icon $average"

[[block]] 
block = "custom"
interval = 10 
command = '''echo "󰈐 $(sensors | grep fan1 | awk '{print $2; exit}')" '''

[[block]]
block = "toggle"
format = "$icon 󰅶 "
command_state = "xset q | grep 'DPMS is Disabled'"
command_on = "xset q -dpms s off"
command_off = "xset q +dpms s on"
state_on = "good"
state_off = "idle"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "net"
format = "{󰖩 $ssid |󰈀 $ssid}"
inactive_format = "󰖪 "
interval = 30

[[block]]
block = "time"
interval = 10
format = " $timestamp.datetime(f:'%a %D %I:%M%p') "

