export GUM_FILTER_TEXT_FOREGROUND="#a6adc8"
export GUM_FILTER_MATCH_FOREGROUND="#eba0ac"
export GUM_FILTER_INDICATOR_FOREGROUND="#89b4fa"
export GUM_FILTER_PROMPT_FOREGROUND="#89dceb"
# export GUM_FILTER_HEADER_FOREGROUND="#fab387"
export GUM_FILTER_PLACEHOLDER_FOREGROUND="#6c7086"
export GUM_FILTER_CURSOR_TEXT_FOREGROUND="#94e2d5"


export GUM_CHOOSE_ITEM_FOREGROUND="#a6adc8"
# export GUM_CHOOSE_MATCH_FOREGROUND="#eba0ac"
# export GUM_CHOOSE_FOREGROUND="#89b4fa"
export GUM_CHOOSE_CURSOR_FOREGROUND="#89dceb"
# export GUM_FILTER_HEADER_FOREGROUND="#fab387"
# export GUM_CHOOSE_PLACEHOLDER_FOREGROUND="#b4befe"
# export GUM_CHOOSE_CURSOR_TEXT_FOREGROUND="#94e2d5"

export GUM_FILE_DIRECTORY_FOREGROUND="#a6adc8"
# export GUM_CHOOSE_MATCH_FOREGROUND="#eba0ac"
export GUM_FILE_FILE_FOREGROUND="#89b4fa"
export GUM_FILE_CURSOR_FOREGROUND="#89dceb"
export GUM_FILE_HEADER_FOREGROUND="#fab387"
# export GUM_E_PLACEHOLDER_FOREGROUND="#b4befe"
export GUM_FILE_SELECTED_FOREGROUND="#94e2d5"


